# Numpy

## Numpy Array Operations

In [ ]:
import numpy as np
temperature_w1 = np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])
print (temperature_w1)


[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


##  Inspections and Properties

In [ ]:
import numpy as np
temperature_w1 = np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])
print (temperature_w1.shape)
print (temperature_w1.dtype)
print (temperature_w1.size)


(7,)
float64
7


##  Array Operations

In [ ]:
import numpy as np
temperature_w1 = np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])
temp_f = (temperature_w1 * 9/5) + 32
print (temp_f)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [ ]:
import numpy as np
temperature_w1 = np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])
max_np = np.max(temperature_w1)
min_np = np.min(temperature_w1)
mean_np = np.mean(temperature_w1)
print (min_np)
print (max_np)
print (mean_np)

20.8
26.1
23.542857142857144


## Array slicing & Indexing

In [ ]:
import numpy as np
temperature_w1 = np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])
first_3_days =temperature_w1[0:3]
print ( first_3_days)


[22.5 25.3 20.8]


In [ ]:
import numpy as np
temperature_w1 = np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])
last_two_weeks =temperature_w1[-2:]
print ( last_two_weeks)

[24.8 21.9]


In [ ]:
import numpy as np
temperature_w1 = np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])
middle_3_days =temperature_w1[2:5]
print ( middle_3_days)


[20.8 23.4 26.1]


## Create 2D Array

In [ ]:
import numpy as np
temperature_1 = np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])
temperature_2 = np.array([19.2,22.5,21.3,24.0,23.5,22.8,20.1])
temperature_w1 = np.array([temperature_1,temperature_2])
print (temperature_w1)


[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [ ]:
import numpy as np
temperature_1 = np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])
temperature_2 = np.array([19.2,22.5,21.3,24.0,23.5,22.8,20.1])
temperature_w1 = np.array([temperature_1,temperature_2])
print (temperature_w1.shape)
print (temperature_w1.dtype)
print (temperature_w1.size)


(2, 7)
float64
14


In [ ]:
import numpy as np
temperature_1 = np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])
temperature_2 = np.array([19.2,22.5,21.3,24.0,23.5,22.8,20.1])
temperature_w1 = np.array([temperature_1,temperature_2])
last_two_weeks =temperature_w1[:,-2:]
print ( last_two_weeks)

[[24.8 21.9]
 [22.8 20.1]]


# pandas

## Creating Pandas Series

In [ ]:
import pandas as pd

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=["Rank1", "Rank2", "Rank3", "Rank4", "Rank5"]
)

print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


## Indexing and Slicing

In [ ]:
import pandas as pd

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=["Rank1", "Rank2", "Rank3", "Rank4", "Rank5"]
)
print(marks[0])

95


/tmp/ipykernel_390/1181282509.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(marks[0])


In [ ]:
print(marks.loc[["Rank1", "Rank2", "Rank3"]])

Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [ ]:
print(marks.iloc[2])

89


In [ ]:
print(marks[marks > 90])

Rank1    95
Rank2    92
dtype: int64


## Mnaipulating Series

In [ ]:
import pandas as pd

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=["Rank1", "Rank2", "Rank3", "Rank4", "Rank5"]
)
marks["Rank1"] = 100
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [ ]:
import pandas as pd

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=["Rank1", "Rank2", "Rank3", "Rank4", "Rank5"]
)
marks = marks.drop("Rank5")
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
dtype: int64


In [ ]:
import pandas as pd

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=["Rank1", "Rank2", "Rank3", "Rank4", "Rank5"]
)
cgpa = marks / 10
print(cgpa)

Rank1    9.5
Rank2    9.2
Rank3    8.9
Rank4    8.5
Rank5    8.0
dtype: float64


# Pandas Data Frame

## Creating Pandas Data Frame

In [ ]:
import pandas as pd

transactions = pd.DataFrame({
    "TransactionID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "ProductCategory": [
        "Electronics", "Clothing", "Electronics", "Furniture", "Clothing",
        "Electronics", "Furniture", "Clothing", "Furniture", "Electronics"
    ],
    "Region": [
        "North", "South", "North", "East", "West",
        "North", "East", "West", "South", "North"
    ],
    "Amount": [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


## Data Exploration

In [ ]:
print(transactions.head())
print(transactions.tail())
print(transactions.shape)
print(transactions.columns)
print(transactions.dtypes)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
(10, 4)
Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')
TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


In [ ]:
print(transactions[["ProductCategory", "Amount"]])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [ ]:
print(transactions.iloc[:, -3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [ ]:
print(transactions.loc[:, ["ProductCategory", "Region", "Amount"]])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [ ]:
filtered = transactions[(transactions["Region"] == "North") & (transactions["Amount"] > 200)]
print(filtered)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [ ]:
print(transactions["ProductCategory"].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [ ]:
print(transactions["Region"].unique())

['North' 'South' 'East' 'West']


In [ ]:
print(transactions.groupby("Region")["Amount"].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


## Manipulating the Data frames

In [ ]:
transactions.loc[transactions["TransactionID"] == 102, "Amount"] = 165
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [ ]:
transactions["Discount"] = transactions["Amount"] * 0.10
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [ ]:
transactions = transactions[transactions["TransactionID"] != 109]
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [ ]:
transactions = transactions.drop("Discount", axis=1)
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
